
dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-11/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: C82hgVRLEitiEC3mjntICo+27g0gbrXycyW1dGsCfFZ0Z2exG3XD5sqMXhW2K8ibaoRaEobuN02P7HFQpa6gVBrP7Woj/YYASNvyI2RqHDD+J/1MIt/VSK+yYNrtnn2Vekl0dyvJ7PvK596ciShE18dwzthafh+7CL0N2Q6r/sklWZhvryQyW0b+dXTsfdD8RUg3LDGEf18WQteXmRNI5JHOZpn93h76LlXVogzCYwyf+j8mGAvLfbBOXu4QFZ9d0yWqEnrTtK3VqVf6/RPMm63a68DRzLTI6OQaq8YhoaNxge6jnddWn1r4eGEv2vwUbS0PZn7TDWfhqCDHVQBcdXT1yGH8vIz7FAoLnUKwQzbl+h2nRMEikpqZabtj8Z/JuoylYLoi1n2FdaRAK1ilTWL6jAqzqWJ/ibQna3poc4YaPXzIDA7AhL/uYs+EUNwRoJdg8TrOPnQRg1w7wa147VFXbzQuEja6VxPwZDQXOQal5JfoBIbSULZULfe7/yO+n29x6t0SVUW02Qv6X75AhW1CRDAksbkfFgM0GJMkNJit+gCZi2dtNitL9BZBgDg9DRRktdQZLwKqHDxYRdfgZcbbIMRkJVpKRL0CoMwXbWYdjOgzhhKYyZsPh/CIdWnfED7sPC5wF8OfkaHgtOFqvfhT2/TTW9ePEkZMwWx6FAo=
