global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#pavel_lukin'
