version: '3.3'
services:
  post_db:
    image: mongo:${VER_DB}
    volumes:
      - post_db:/data/db
    networks:
      - back_net

  ui:
    image: ${USERNAME}/ui
    ports:
      - ${PORT_INT}:${PORT_EXT}/tcp
    networks:
      - front_net

  post:
    image: ${USERNAME}/post
    networks:
      - back_net
      - front_net

  comment:
    image: ${USERNAME}/comment
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  front_net:
  back_net:
